function createlegend(axes1)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 02-Dec-2007 13:08:37

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[1/OSR 0.6328 0.1563 0.1333]);

